## Summary

We implemented two Bayesian Networks using the Expectation-Maximization (EM) algorithm for fraud detection. The small network used three features while the larger network incorporated additional variables. Both models used EM to handle latent variables and estimate conditional probability distributions for predicting fraudulent transactions.

## Methodology

### Small Bayesian Network

**Data Preprocessing:**
- Features: `fraud_bool`, `customer_age`, `income`, `credit_risk_score`
- Discretized continuous variables into 3 bins each (e.g., young/middle-aged/old for age)

**Model Structure:**
- Parent node: `fraud_bool`
- Child nodes: `age_bin`, `income_bin`, `credit_bin`
- Added latent variable `bank_bin` (3 states, never observed)

**Training & Evaluation:**
- Trained using ExpectationMaximization estimator
- Used Variable Elimination for inference on test data
- Evaluated with ROC-AUC score and classification report

### Larger Bayesian Network

**Data Preprocessing:**
- Same binning approach for other variables

**Training & Evaluation:**
- Same EM training approach with latent variable specification
- Evaluated using identical metrics to compare performance with small network

**Key Difference:** The larger network includes more features to potentially capture richer fraud patterns.

In [3]:
!pip install pgmpy

Collecting pgmpy
  Downloading pgmpy-1.0.0-py3-none-any.whl.metadata (9.4 kB)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from pgmpy) (3.6)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pgmpy) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from pgmpy) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from pgmpy) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from pgmpy) (2.2.2)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from pgmpy) (2.9.0+cu126)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from pgmpy) (0.14.5)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from pgmpy) (4.67.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from pgmpy) (1.5.2)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.12/dist-packages (from pgmpy) (3.4.0)
Collecting pyro-ppl (from pgmpy)
  Downloading pyro_ppl-1.9.1-py3-none-any.whl.metadata (7.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->pgmpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->pgmpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->pgmpy) (2025.2)
Collecting pyro-api>=0.1.1 (from pyro-ppl->pgmpy)
  Downloading pyro_api-0.1.2-py3-none-any.whl.metadata (2.5 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch->pgmpy) (3.5.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->pgmpy) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pgmpy) (1.0.2)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.12/dist-packages (from statsmodels->pgmpy) (25.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->pgmpy) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->pgmpy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->pgmpy) (3.0.3)
Downloading pgmpy-1.0.0-py3-none-any.whl (2.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 17.4 MB/s eta 0:00:00
Downloading pyro_ppl-1.9.1-py3-none-any.whl (755 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 756.0/756.0 kB 35.0 MB/s eta 0:00:00
Downloading pyro_api-0.1.2-py3-none-any.whl (11 kB)
Installing collected packages: pyro-api, pyro-ppl, pgmpy
Successfully installed pgmpy-1.0.0 pyro-api-0.1.2 pyro-ppl-1.9.1

**Imports**

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pgmpy.estimators import MaximumLikelihoodEstimator, ExpectationMaximization
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.inference import VariableElimination
from sklearn.metrics import classification_report

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/150A datasets/our 10 selected features/balanced_train.csv')

In [ ]:
# Using discrete columns now instead of continous values
bn_df = df[['fraud_bool', 'age_bin', 'income_bin', 'credit_bin']].astype(str)

bn_df

      fraud_bool      age_bin    income_bin         credit_bin
0              0        young   lower class  high credit score
1              0        young   lower class   low credit score
2              0        young  middle class   low credit score
3              0        young   lower class   low credit score
4              1        young   lower class  high credit score
...          ...          ...           ...                ...
52934          0        young   upper class  high credit score
52935          0  middle-aged  middle class   low credit score
52936          0  middle-aged   lower class   mid credit score
52937          0        young  middle class   mid credit score
52938          0  middle-aged  middle class  high credit score

[52939 rows x 4 columns]

In [ ]:
# defining the BN relationship
model = DiscreteBayesianNetwork([('fraud_bool', 'age_bin'),('fraud_bool', 'income_bin'),('fraud_bool', 'credit_bin'), ('fraud_bool', 'bank_bin')])
# making bank_bin a hidden/latent variable so that it is not used for EM
model.latents.add('bank_bin')
model.fit(bn_df, estimator=ExpectationMaximization, latent_card={'bank_bin': 3})

for cpt in model.get_cpds():
    print(cpt)

  0%|          | 0/100 [00:00<?, ?it/s]

+---------------+----------+
| fraud_bool(0) | 0.833336 |
+---------------+----------+
| fraud_bool(1) | 0.166664 |
+---------------+----------+
+--------------------------+---------------------+---------------------+
| fraud_bool               | fraud_bool(0)       | fraud_bool(1)       |
+--------------------------+---------------------+---------------------+
| income_bin(lower class)  | 0.3623401940339106  | 0.2044656012694095  |
+--------------------------+---------------------+---------------------+
| income_bin(middle class) | 0.42193308550185876 | 0.3599682647625524  |
+--------------------------+---------------------+---------------------+
| income_bin(upper class)  | 0.21572672046423066 | 0.43556613396803806 |
+--------------------------+---------------------+---------------------+
+----------------------+---------------------+---------------------+
| fraud_bool           | fraud_bool(0)       | fraud_bool(1)       |
+----------------------+---------------------+---------------------+
| age_bin(middle-aged) | 0.2353341191404479  | 0.25966224640145075 |
+----------------------+---------------------+---------------------+
| age_bin(old)         | 0.17991205004986852 | 0.3877365975291851  |
+----------------------+---------------------+---------------------+
| age_bin(young)       | 0.5847538308096836  | 0.35260115606936415 |
+----------------------+---------------------+---------------------+
+-------------------------------+---------------------+---------------------+
| fraud_bool                    | fraud_bool(0)       | fraud_bool(1)       |
+-------------------------------+---------------------+---------------------+
| credit_bin(high credit score) | 0.3314897089491341  | 0.5900487362575088  |
+-------------------------------+---------------------+---------------------+
| credit_bin(low credit score)  | 0.33450448816755823 | 0.19981865578601382 |
+-------------------------------+---------------------+---------------------+
| credit_bin(mid credit score)  | 0.33400580288330767 | 0.2101326079564774  |
+-------------------------------+---------------------+---------------------+
+-------------+---------------------+---------------------+
| fraud_bool  | fraud_bool(0)       | fraud_bool(1)       |
+-------------+---------------------+---------------------+
| bank_bin(0) | 0.273280603521432   | 0.3859952772221528  |
+-------------+---------------------+---------------------+
| bank_bin(1) | 0.15357413274817203 | 0.45476301531089497 |
+-------------+---------------------+---------------------+
| bank_bin(2) | 0.573145263730396   | 0.15924170746695218 |
+-------------+---------------------+---------------------+

In [ ]:
# using the testing dataset now
df2 = pd.read_csv('/content/drive/MyDrive/150A datasets/our 10 selected features/balanced_test.csv')

X_test_transformed = df2[['fraud_bool', 'age_bin', 'income_bin', 'credit_bin']].astype(str)

# getting the true fraud values
y_test = X_test_transformed['fraud_bool'].astype(int)

# Inference using built-in library function
inference = VariableElimination(model)

y_prob_em = [] # list for predicted probabilities of fraud
y_pred_em = [] # either 0 or 1

for _, row in X_test_transformed.iterrows():
    evidence = {'age_bin': row['age_bin'], 'income_bin': row['income_bin'], 'credit_bin': row['credit_bin']}
    result = inference.query(variables=['fraud_bool'], evidence=evidence)
    prob = result.values[1]
    y_prob_em.append(prob)
    if prob > 0.5:
        y_pred_em.append(1)
    else:
        y_pred_em.append(0)


print('\nModel Evaluation of EM')
print(f'Classification Report:\n{classification_report(y_test, y_pred_em)}')

Model Evaluation of EM
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.98      0.91     11029
           1       0.54      0.12      0.20      2206

    accuracy                           0.84     13235
   macro avg       0.69      0.55      0.56     13235
weighted avg       0.80      0.84      0.79     13235

# Larger Baysian Network

In [ ]:
big_df = pd.read_csv('/content/drive/MyDrive/150A datasets/our 10 selected features/balanced_train.csv')
big_df_test= pd.read_csv('/content/drive/MyDrive/150A datasets/our 10 selected features/balanced_test.csv')

In [ ]:
big_df

,fraud_bool,customer_age,name_email_similarity,income,email_is_free,bank_months_count,payment_type,keep_alive_session,has_other_cards,velocity_24h,credit_risk_score
0,0,30,0.320034,0.3,0,-1,2,0,1,4654.102710,202
1,0,20,0.156357,0.2,0,15,1,1,1,4181.158461,36
2,0,10,0.365924,0.5,0,-1,2,0,0,6053.582812,49
3,0,30,0.758116,0.4,1,1,0,1,0,4194.135820,46
4,1,30,0.025710,0.1,1,15,1,1,0,4094.410353,280
...,...,...,...,...,...,...,...,...,...,...,...
52934,0,30,0.879008,0.9,0,-1,2,1,1,5123.788798,342
52935,0,40,0.159300,0.8,1,28,1,1,0,3632.646724,75
52936,0,40,0.835903,0.2,1,16,1,1,0,3288.816690,109
52937,0,30,0.084266,0.8,1,28,0,0,0,5634.782089,116
52938,0,40,0.746441,0.8,0,28,3,1,1,2976.767142,172

In [ ]:
bn_df = big_df[['fraud_bool', 'age_bin', 'income_bin', 'credit_bin', 'bank_bin', 'name_email_bin', 'payment_type', 'keep_alive_session', 'has_other_cards', 'velocity_24h_bin', 'email_is_free']].astype(str)


bn_df

,fraud_bool,age_bin,income_bin,credit_bin,bank_bin,name_email_bin,payment_type,keep_alive_session,has_other_cards,velocity_24h_bin,email_is_free
0,0,young,lower class,high credit score,short term,medium similarity,2,0,1,medium,0
1,0,young,lower class,low credit score,medium term,low similar,1,1,1,medium,0
2,0,young,middle class,low credit score,short term,medium similarity,2,0,0,high,0
3,0,young,lower class,low credit score,short term,high similarity,0,1,0,medium,1
4,1,young,lower class,high credit score,medium term,low similar,1,1,0,medium,1
...,...,...,...,...,...,...,...,...,...,...,...
52934,0,young,upper class,high credit score,short term,high similarity,2,1,1,medium,0
52935,0,middle-aged,middle class,low credit score,long term,low similar,1,1,0,low,1
52936,0,middle-aged,lower class,mid credit score,medium term,high similarity,1,1,0,low,1
52937,0,young,middle class,mid credit score,long term,low similar,0,0,0,high,1
52938,0,middle-aged,middle class,high credit score,long term,high similarity,3,1,1,low,0

In [ ]:
model = DiscreteBayesianNetwork([('fraud_bool', 'age_bin'),('fraud_bool', 'income_bin'),('fraud_bool', 'credit_bin'), ('fraud_bool', 'bank_bin'),
                                 ('fraud_bool', 'name_email_bin'),('fraud_bool', 'payment_type'),('fraud_bool', 'keep_alive_session'),
                                 ('fraud_bool', 'has_other_cards'),('fraud_bool', 'velocity_24h_bin'),('fraud_bool', 'email_is_free')])
model.latents.add('bank_bin')
model.fit(bn_df, estimator=ExpectationMaximization, latent_card={'bank_bin': 3})


for cpt in model.get_cpds():
    print(cpt)

  0%|          | 0/100 [00:00<?, ?it/s]

+--------------------+---------------------+---------------------+
| fraud_bool         | fraud_bool(0)       | fraud_bool(1)       |
+--------------------+---------------------+---------------------+
| has_other_cards(0) | 0.7759996373197933  | 0.9144281990252748  |
+--------------------+---------------------+---------------------+
| has_other_cards(1) | 0.22400036268020673 | 0.08557180097472515 |
+--------------------+---------------------+---------------------+
+-------------------------------+---------------------+---------------------+
| fraud_bool                    | fraud_bool(0)       | fraud_bool(1)       |
+-------------------------------+---------------------+---------------------+
| credit_bin(high credit score) | 0.3314897089491341  | 0.5900487362575088  |
+-------------------------------+---------------------+---------------------+
| credit_bin(low credit score)  | 0.33450448816755823 | 0.19981865578601382 |
+-------------------------------+---------------------+---------------------+
| credit_bin(mid credit score)  | 0.33400580288330767 | 0.2101326079564774  |
+-------------------------------+---------------------+---------------------+
+--------------------------+---------------------+---------------------+
| fraud_bool               | fraud_bool(0)       | fraud_bool(1)       |
+--------------------------+---------------------+---------------------+
| income_bin(lower class)  | 0.3623401940339106  | 0.2044656012694095  |
+--------------------------+---------------------+---------------------+
| income_bin(middle class) | 0.42193308550185876 | 0.3599682647625524  |
+--------------------------+---------------------+---------------------+
| income_bin(upper class)  | 0.21572672046423066 | 0.43556613396803806 |
+--------------------------+---------------------+---------------------+
+-----------------+----------------------+------------------------+
| fraud_bool      | fraud_bool(0)        | fraud_bool(1)          |
+-----------------+----------------------+------------------------+
| payment_type(0) | 0.25383080968356153  | 0.12614756885413125    |
+-----------------+----------------------+------------------------+
| payment_type(1) | 0.37265391241273005  | 0.3743624617477049     |
+-----------------+----------------------+------------------------+
| payment_type(2) | 0.25421615740320974  | 0.38138955003966907    |
+-----------------+----------------------+------------------------+
| payment_type(3) | 0.11904977785837338  | 0.11798707922475349    |
+-----------------+----------------------+------------------------+
| payment_type(4) | 0.000249342642125306 | 0.00011334013374135781 |
+-----------------+----------------------+------------------------+
+--------------------------+---------------------+--------------------+
| fraud_bool               | fraud_bool(0)       | fraud_bool(1)      |
+--------------------------+---------------------+--------------------+
| velocity_24h_bin(high)   | 0.32974431045425695 | 0.2953643885299785 |
+--------------------------+---------------------+--------------------+
| velocity_24h_bin(low)    | 0.33606854655907153 | 0.3478408704522271 |
+--------------------------+---------------------+--------------------+
| velocity_24h_bin(medium) | 0.3341871429866715  | 0.3567947410177944 |
+--------------------------+---------------------+--------------------+
+---------------+----------+
| fraud_bool(0) | 0.833336 |
+---------------+----------+
| fraud_bool(1) | 0.166664 |
+---------------+----------+
+-----------------------------------+---------------------+--------------------+
| fraud_bool                        | fraud_bool(0)       | fraud_bool(1)      |
+-----------------------------------+---------------------+--------------------+
| name_email_bin(high similarity)   | 0.3341191404479101  | 0.2563753825229514 |
+-----------------------------------+---------------------+--------------------+
| name_email_bin(low similar)       | 0.33248707951763534 | 0.5150175677207299 |
+-----------------------------------+---------------------+--------------------+
| name_email_bin(medium similarity) | 0.33339378003445463 | 0.2286070497563187 |
+-----------------------------------+---------------------+--------------------+
+-----------------------+--------------------+---------------------+
| fraud_bool            | fraud_bool(0)      | fraud_bool(1)       |
+-----------------------+--------------------+---------------------+
| keep_alive_session(0) | 0.4220464230664612 | 0.6619063810495296  |
+-----------------------+--------------------+---------------------+
| keep_alive_session(1) | 0.5779535769335389 | 0.33809361895047035 |
+-----------------------+--------------------+---------------------+
+------------------+---------------------+---------------------+
| fraud_bool       | fraud_bool(0)       | fraud_bool(1)       |
+------------------+---------------------+---------------------+
| email_is_free(0) | 0.47304832713754646 | 0.33900034002040125 |
+------------------+---------------------+---------------------+
| email_is_free(1) | 0.5269516728624535  | 0.6609996599795988  |
+------------------+---------------------+---------------------+
+----------------------+---------------------+---------------------+
| fraud_bool           | fraud_bool(0)       | fraud_bool(1)       |
+----------------------+---------------------+---------------------+
| age_bin(middle-aged) | 0.2353341191404479  | 0.25966224640145075 |
+----------------------+---------------------+---------------------+
| age_bin(old)         | 0.17991205004986852 | 0.3877365975291851  |
+----------------------+---------------------+---------------------+
| age_bin(young)       | 0.5847538308096836  | 0.35260115606936415 |
+----------------------+---------------------+---------------------+
+-------------+---------------------+---------------------+
| fraud_bool  | fraud_bool(0)       | fraud_bool(1)       |
+-------------+---------------------+---------------------+
| bank_bin(0) | 0.29722835108285356 | 0.44393800587995114 |
+-------------+---------------------+---------------------+
| bank_bin(1) | 0.21348895356986985 | 0.08265919040817109 |
+-------------+---------------------+---------------------+
| bank_bin(2) | 0.4892826953472766  | 0.47340280371187776 |
+-------------+---------------------+---------------------+

In [ ]:
target = 'fraud_bool'

X_train = big_df.drop(target, axis=1).astype(str)
y_train = big_df[target]
X_test = big_df_test.drop(target, axis=1).astype(str)
y_test = big_df_test[target]

inference = VariableElimination(model)

y_prob_em = [] # list for predicted probabilities of fraud
y_pred_em = [] # either 0 or 1

for _, row in X_test.iterrows():
    evidence = {'age_bin': row['age_bin'], 'income_bin': row['income_bin'], 'credit_bin': row['credit_bin'],
                'name_email_bin': row['name_email_bin'], 'payment_type': row['payment_type'],'keep_alive_session': row['keep_alive_session'],
                'velocity_24h_bin': row['velocity_24h_bin'],'email_is_free': row['email_is_free']}
    result = inference.query(variables=['fraud_bool'], evidence=evidence)
    prob = result.values[1]
    y_prob_em.append(prob)
    if prob > 0.5:
        y_pred_em.append(1)
    else:
        y_pred_em.append(0)


print('\nModel Evaluation of EM')
print(f'Classification Report:\n{classification_report(y_test, y_pred_em)}')

Model Evaluation of EM
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.96      0.91     11029
           1       0.59      0.27      0.37      2206

    accuracy                           0.85     13235
   macro avg       0.73      0.62      0.64     13235
weighted avg       0.82      0.85      0.82     13235

# Small Bayesian Network (new balanced data)

In [5]:
df_2 = pd.read_csv('/balanced_train.csv')

In [7]:
# Using discrete columns now instead of continous values
bn_df2 = df_2[['fraud_bool', 'age_bin', 'income_bin', 'credit_bin']].astype(str)

bn_df2

      fraud_bool      age_bin    income_bin        credit_bin
0              0        young   lower class       high credit
1              0        young  middle class   very low credit
2              0  middle-aged  middle class       high credit
3              0        young   upper class        low credit
4              1        young   lower class  very high credit
...          ...          ...           ...               ...
52934          0  middle-aged  middle class  very high credit
52935          0  middle-aged   lower class     medium credit
52936          0  middle-aged  middle class  very high credit
52937          0          old   lower class  very high credit
52938          0        young   lower class        low credit

[52939 rows x 4 columns]

In [8]:
# defining the BN relationship
model2 = DiscreteBayesianNetwork([('fraud_bool', 'age_bin'),('fraud_bool', 'income_bin'),('fraud_bool', 'credit_bin'), ('fraud_bool', 'bank_bin')])
# making bank_bin a hidden/latent variable so that it is not used for EM
model2.latents.add('bank_bin')
model2.fit(bn_df2, estimator=ExpectationMaximization, latent_card={'bank_bin': 3})

for cpt in model2.get_cpds():
    print(cpt)

  0%|          | 0/100 [00:00<?, ?it/s]

+---------------+----------+
| fraud_bool(0) | 0.833336 |
+---------------+----------+
| fraud_bool(1) | 0.166664 |
+---------------+----------+
+--------------------------+---------------------+---------------------+
| fraud_bool               | fraud_bool(0)       | fraud_bool(1)       |
+--------------------------+---------------------+---------------------+
| income_bin(lower class)  | 0.36435760268383355 | 0.2044656012694095  |
+--------------------------+---------------------+---------------------+
| income_bin(middle class) | 0.4155181793453622  | 0.3599682647625524  |
+--------------------------+---------------------+---------------------+
| income_bin(upper class)  | 0.22012421797080425 | 0.43556613396803806 |
+--------------------------+---------------------+---------------------+
+------------------------------+---------------------+---------------------+
| fraud_bool                   | fraud_bool(0)       | fraud_bool(1)       |
+------------------------------+---------------------+---------------------+
| credit_bin(high credit)      | 0.20303291322876055 | 0.20491896180437494 |
+------------------------------+---------------------+---------------------+
| credit_bin(low credit)       | 0.1962779943784568  | 0.11991386149835657 |
+------------------------------+---------------------+---------------------+
| credit_bin(medium credit)    | 0.20301024571584006 | 0.11538025614870226 |
+------------------------------+---------------------+---------------------+
| credit_bin(very high credit) | 0.19326321516003264 | 0.442819902527485   |
+------------------------------+---------------------+---------------------+
| credit_bin(very low credit)  | 0.20441563151690997 | 0.11696701802108127 |
+------------------------------+---------------------+---------------------+
+----------------------+---------------------+---------------------+
| fraud_bool           | fraud_bool(0)       | fraud_bool(1)       |
+----------------------+---------------------+---------------------+
| age_bin(middle-aged) | 0.23977695167286245 | 0.25966224640145075 |
+----------------------+---------------------+---------------------+
| age_bin(old)         | 0.17857466678756007 | 0.3877365975291851  |
+----------------------+---------------------+---------------------+
| age_bin(young)       | 0.5816483815395774  | 0.35260115606936415 |
+----------------------+---------------------+---------------------+
+-------------+--------------------+---------------------+
| fraud_bool  | fraud_bool(0)      | fraud_bool(1)       |
+-------------+--------------------+---------------------+
| bank_bin(0) | 0.3477507520805306 | 0.4698744170501933  |
+-------------+--------------------+---------------------+
| bank_bin(1) | 0.5403573258933515 | 0.3703736953174301  |
+-------------+--------------------+---------------------+
| bank_bin(2) | 0.1118919220261179 | 0.15975188763237666 |
+-------------+--------------------+---------------------+

In [10]:
# using the testing dataset now
df_2_test = pd.read_csv('/balanced_test.csv')

X_test_transformed = df_2_test[['fraud_bool', 'age_bin', 'income_bin', 'credit_bin']].astype(str)

# getting the true fraud values
y_test = X_test_transformed['fraud_bool'].astype(int)

# Inference using built-in library function
inference = VariableElimination(model2)

y_prob_em = [] # list for predicted probabilities of fraud
y_pred_em = [] # either 0 or 1

for _, row in X_test_transformed.iterrows():
    evidence = {'age_bin': row['age_bin'], 'income_bin': row['income_bin'], 'credit_bin': row['credit_bin']}
    result = inference.query(variables=['fraud_bool'], evidence=evidence)
    prob = result.values[1]
    y_prob_em.append(prob)
    if prob > 0.5:
        y_pred_em.append(1)
    else:
        y_pred_em.append(0)


print('\nModel Evaluation of EM')
print(f'Classification Report:\n{classification_report(y_test, y_pred_em)}')

Model Evaluation of EM
Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.99      0.91     11029
           1       0.57      0.10      0.17      2206

    accuracy                           0.84     13235
   macro avg       0.71      0.54      0.54     13235
weighted avg       0.80      0.84      0.79     13235

# Large Baysian Network (new balanced data)

In [11]:
big_df2 = pd.read_csv('/balanced_train.csv')
big_df2_test= pd.read_csv('/balanced_test.csv')

In [12]:
big_df2

,fraud_bool,email_is_free,payment_type,keep_alive_session,has_other_cards,age_bin,income_bin,credit_bin,bank_bin,name_email_bin,velocity_24h_bin
0,0,0,2,1,0,young,lower class,high credit,short term,low similarity,very low
1,0,1,1,0,0,young,middle class,very low credit,medium term,very low similarity,low
2,0,1,3,1,0,middle-aged,middle class,high credit,short term,very low similarity,high
3,0,1,1,1,0,young,upper class,low credit,short term,high similarity,low
4,1,1,1,1,0,young,lower class,very high credit,medium term,very low similarity,low
...,...,...,...,...,...,...,...,...,...,...,...
52934,0,0,0,1,0,middle-aged,middle class,very high credit,long term,very high similarity,medium
52935,0,1,0,0,1,middle-aged,lower class,medium credit,short term,very high similarity,low
52936,0,0,0,0,0,middle-aged,middle class,very high credit,long term,very low similarity,high
52937,0,1,1,1,1,old,lower class,very high credit,short term,very low similarity,low
52938,0,0,2,1,0,young,lower class,low credit,short term,medium similarity,very high

In [16]:
bn_df2 = big_df2[['fraud_bool', 'age_bin', 'income_bin', 'credit_bin', 'bank_bin', 'name_email_bin', 'payment_type', 'keep_alive_session', 'has_other_cards', 'velocity_24h_bin', 'email_is_free']].astype(str)


bn_df2

,fraud_bool,age_bin,income_bin,credit_bin,bank_bin,name_email_bin,payment_type,keep_alive_session,has_other_cards,velocity_24h_bin,email_is_free
0,0,young,lower class,high credit,short term,low similarity,2,1,0,very low,0
1,0,young,middle class,very low credit,medium term,very low similarity,1,0,0,low,1
2,0,middle-aged,middle class,high credit,short term,very low similarity,3,1,0,high,1
3,0,young,upper class,low credit,short term,high similarity,1,1,0,low,1
4,1,young,lower class,very high credit,medium term,very low similarity,1,1,0,low,1
...,...,...,...,...,...,...,...,...,...,...,...
52934,0,middle-aged,middle class,very high credit,long term,very high similarity,0,1,0,medium,0
52935,0,middle-aged,lower class,medium credit,short term,very high similarity,0,0,1,low,1
52936,0,middle-aged,middle class,very high credit,long term,very low similarity,0,0,0,high,0
52937,0,old,lower class,very high credit,short term,very low similarity,1,1,1,low,1
52938,0,young,lower class,low credit,short term,medium similarity,2,1,0,very high,0

In [17]:
model2 = DiscreteBayesianNetwork([('fraud_bool', 'age_bin'),('fraud_bool', 'income_bin'),('fraud_bool', 'credit_bin'), ('fraud_bool', 'bank_bin'),
                                 ('fraud_bool', 'name_email_bin'),('fraud_bool', 'payment_type'),('fraud_bool', 'keep_alive_session'),
                                 ('fraud_bool', 'has_other_cards'),('fraud_bool', 'velocity_24h_bin'),('fraud_bool', 'email_is_free')])
model2.latents.add('bank_bin')
model2.fit(bn_df2, estimator=ExpectationMaximization, latent_card={'bank_bin': 3})


for cpt in model2.get_cpds():
    print(cpt)

  0%|          | 0/100 [00:00<?, ?it/s]

+--------------------+-------------------+---------------------+
| fraud_bool         | fraud_bool(0)     | fraud_bool(1)       |
+--------------------+-------------------+---------------------+
| has_other_cards(0) | 0.775704959651827 | 0.9144281990252748  |
+--------------------+-------------------+---------------------+
| has_other_cards(1) | 0.224295040348173 | 0.08557180097472515 |
+--------------------+-------------------+---------------------+
+----------------------+---------------------+---------------------+
| fraud_bool           | fraud_bool(0)       | fraud_bool(1)       |
+----------------------+---------------------+---------------------+
| age_bin(middle-aged) | 0.23977695167286245 | 0.25966224640145075 |
+----------------------+---------------------+---------------------+
| age_bin(old)         | 0.17857466678756007 | 0.3877365975291851  |
+----------------------+---------------------+---------------------+
| age_bin(young)       | 0.5816483815395774  | 0.35260115606936415 |
+----------------------+---------------------+---------------------+
+-----------------------------+---------------------+---------------------+
| fraud_bool                  | fraud_bool(0)       | fraud_bool(1)       |
+-----------------------------+---------------------+---------------------+
| velocity_24h_bin(high)      | 0.2001088040620183  | 0.19675847217499717 |
+-----------------------------+---------------------+---------------------+
| velocity_24h_bin(low)       | 0.1978193852570496  | 0.16332313272129662 |
+-----------------------------+---------------------+---------------------+
| velocity_24h_bin(medium)    | 0.19988212893281349 | 0.23654085911821376 |
+-----------------------------+---------------------+---------------------+
| velocity_24h_bin(very high) | 0.20396228125850033 | 0.1609429899127281  |
+-----------------------------+---------------------+---------------------+
| velocity_24h_bin(very low)  | 0.1982274004896183  | 0.24243454607276438 |
+-----------------------------+---------------------+---------------------+
+------------------+--------------------+---------------------+
| fraud_bool       | fraud_bool(0)      | fraud_bool(1)       |
+------------------+--------------------+---------------------+
| email_is_free(0) | 0.4730709946504669 | 0.33900034002040125 |
+------------------+--------------------+---------------------+
| email_is_free(1) | 0.526929005349533  | 0.6609996599795988  |
+------------------+--------------------+---------------------+
+-----------------------+--------------------+---------------------+
| fraud_bool            | fraud_bool(0)      | fraud_bool(1)       |
+-----------------------+--------------------+---------------------+
| keep_alive_session(0) | 0.4224771058119503 | 0.6619063810495296  |
+-----------------------+--------------------+---------------------+
| keep_alive_session(1) | 0.5775228941880497 | 0.33809361895047035 |
+-----------------------+--------------------+---------------------+
+--------------------------+---------------------+---------------------+
| fraud_bool               | fraud_bool(0)       | fraud_bool(1)       |
+--------------------------+---------------------+---------------------+
| income_bin(lower class)  | 0.36435760268383355 | 0.2044656012694095  |
+--------------------------+---------------------+---------------------+
| income_bin(middle class) | 0.4155181793453622  | 0.3599682647625524  |
+--------------------------+---------------------+---------------------+
| income_bin(upper class)  | 0.22012421797080425 | 0.43556613396803806 |
+--------------------------+---------------------+---------------------+
+------------------------------+---------------------+---------------------+
| fraud_bool                   | fraud_bool(0)       | fraud_bool(1)       |
+------------------------------+---------------------+---------------------+
| credit_bin(high credit)      | 0.20303291322876055 | 0.20491896180437494 |
+------------------------------+---------------------+---------------------+
| credit_bin(low credit)       | 0.1962779943784568  | 0.11991386149835657 |
+------------------------------+---------------------+---------------------+
| credit_bin(medium credit)    | 0.20301024571584006 | 0.11538025614870226 |
+------------------------------+---------------------+---------------------+
| credit_bin(very high credit) | 0.19326321516003264 | 0.442819902527485   |
+------------------------------+---------------------+---------------------+
| credit_bin(very low credit)  | 0.20441563151690997 | 0.11696701802108127 |
+------------------------------+---------------------+---------------------+
+-----+---------------------+
| ... | fraud_bool(1)       |
+-----+---------------------+
| ... | 0.15935622804034907 |
+-----+---------------------+
| ... | 0.22282670293550946 |
+-----+---------------------+
| ... | 0.12558086818542447 |
+-----+---------------------+
| ... | 0.13929502436812877 |
+-----+---------------------+
| ... | 0.35294117647058826 |
+-----+---------------------+
+---------------+----------+
| fraud_bool(0) | 0.833336 |
+---------------+----------+
| fraud_bool(1) | 0.166664 |
+---------------+----------+
+-----------------+-----------------------+------------------------+
| fraud_bool      | fraud_bool(0)         | fraud_bool(1)          |
+-----------------+-----------------------+------------------------+
| payment_type(0) | 0.26033638589173996   | 0.12614756885413125    |
+-----------------+-----------------------+------------------------+
| payment_type(1) | 0.36938979055218063   | 0.3743624617477049     |
+-----------------+-----------------------+------------------------+
| payment_type(2) | 0.25081603046513734   | 0.38138955003966907    |
+-----------------+-----------------------+------------------------+
| payment_type(3) | 0.11900444283253242   | 0.11798707922475349    |
+-----------------+-----------------------+------------------------+
| payment_type(4) | 0.0004533502584096473 | 0.00011334013374135781 |
+-----------------+-----------------------+------------------------+
+-------------+---------------------+----------------------+
| fraud_bool  | fraud_bool(0)       | fraud_bool(1)        |
+-------------+---------------------+----------------------+
| bank_bin(0) | 0.5833599854256591  | 0.578769125494565    |
+-------------+---------------------+----------------------+
| bank_bin(1) | 0.39769445675369564 | 0.41098355566646433  |
+-------------+---------------------+----------------------+
| bank_bin(2) | 0.01894555782064517 | 0.010247318838970653 |
+-------------+---------------------+----------------------+

In [19]:
target = 'fraud_bool'

X_train = big_df2.drop(target, axis=1).astype(str)
y_train = big_df2[target]
X_test = big_df2_test.drop(target, axis=1).astype(str)
y_test = big_df2_test[target]

inference = VariableElimination(model2)

y_prob_em = [] # list for predicted probabilities of fraud
y_pred_em = [] # either 0 or 1

for _, row in X_test.iterrows():
    evidence = {'age_bin': row['age_bin'], 'income_bin': row['income_bin'], 'credit_bin': row['credit_bin'],
                'name_email_bin': row['name_email_bin'], 'payment_type': row['payment_type'],'keep_alive_session': row['keep_alive_session'],
                'velocity_24h_bin': row['velocity_24h_bin'],'email_is_free': row['email_is_free']}
    result = inference.query(variables=['fraud_bool'], evidence=evidence)
    prob = result.values[1]
    y_prob_em.append(prob)
    if prob > 0.5:
        y_pred_em.append(1)
    else:
        y_pred_em.append(0)


print('\nModel Evaluation of EM with new balanced data')
print(f'Classification Report:\n{classification_report(y_test, y_pred_em)}')

Model Evaluation of EM with new balanced data
Classification Report:
              precision    recall  f1-score   support

           0       0.87      0.95      0.91     11029
           1       0.57      0.30      0.39      2206

    accuracy                           0.85     13235
   macro avg       0.72      0.63      0.65     13235
weighted avg       0.82      0.85      0.82     13235